// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SendRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<main.APIResponse>;
